development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE_DEVELOPMENT"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE_PRODUCTION"] %>

test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE_TEST"] %>
